import {THREE,mat,line,label} from '../scene-kit.js';
import {study,fiberTexture} from '../study-kit.js';
import {loadAnatomy,anatomySources,anatomyCredit} from '../anatomy-assets.js';
const MUSCLES=['FMA13408','FMA13409','FMA34680','FMA34681','FMA34682','FMA34683','FMA34684','FMA34685','FMA34690','FMA34691','FMA45874','FMA45875','FMA79979','FMA79980','FMA37684','FMA37685','FMA37686','FMA37687','FMA37695','FMA37696','FMA37697','FMA37698','FMA37699','FMA37700','FMA13377','FMA13378','FMA37668','FMA37669'];
const BONES=['FMA23130','FMA23131','FMA23464','FMA23465','FMA23467','FMA23468','FMA7487','FMA13322','FMA13323','FMA13395','FMA13396','FMA7486','FMA7857','FMA7987','FMA7882','FMA8012','FMA7909','FMA8039','FMA7957','FMA8148'];
export async function createScene(){
 const texture=fiberTexture('#b57976'),bones=new Set(BONES);
 const {group,objects}=await loadAnatomy([...MUSCLES,...BONES],{center:[0,-112,1140],scale:.0068,material:(id,name)=>bones.has(id)?mat('#dac9aa',.62):new THREE.MeshPhysicalMaterial({color:/deltoid/.test(name)?'#be9691':/biceps/.test(name)?'#c79389':'#b4827e',map:texture,bumpMap:texture,bumpScale:.014,roughness:.59,clearcoat:.05,side:THREE.DoubleSide})});
 let focus='all',separation=0,boneView=false;const annotations=new THREE.Group();group.add(annotations);annotations.visible=false;
 for(const [text,p,q] of [['PECTORALIS',[.55,1,.45],[1.8,1.25,.8]],['DELTOID',[-1.16,1.05,.1],[-2.15,1.2,.4]],['BICEPS',[-1.45,.3,.1],[-2.2,.05,.5]],['RECTUS ABDOMINIS',[.2,-1.5,.6],[1.35,-1.65,.9]]]){const mark=new THREE.Group();mark.userData.family=text.toLowerCase().split(' ')[0];mark.userData.side=Math.sign(p[0]);line([p,q],'#a99483',mark,.5);label(text,q,'#d6c1aa',.12,mark);annotations.add(mark);}
 function refresh(){for(const mark of annotations.children){mark.visible=!boneView&&(focus==='all'||mark.userData.family===focus);mark.position.set(mark.userData.side*separation*.7,0,separation*.18);}for(const o of objects){const isBone=bones.has(o.userData.id),matches=focus==='all'||o.userData.name.includes(focus);o.visible=isBone||(!boneView&&matches);const side=o.userData.center.x<0?-1:1;o.position.x=isBone?0:side*separation*.7;o.position.z=isBone?0:separation*.18;}}
 const reset=()=>{focus='all';separation=0;boneView=false;annotations.visible=false;refresh();};reset();
 return study(group,{reset,controls:[{id:'region',label:'Focus a muscle family',type:'select',options:[{value:'all',label:'Selected upper-body muscles'},{value:'pectoralis',label:'Pectoralis major'},{value:'deltoid',label:'Deltoid'},{value:'biceps',label:'Biceps brachii'},{value:'triceps',label:'Triceps brachii'},{value:'brachialis',label:'Brachialis'},{value:'rectus',label:'Rectus abdominis'}],get:()=>focus,set:v=>{focus=v;boneView=false;refresh();}},{id:'separation',label:'Separate muscles from the framework',type:'range',min:0,max:1,step:.01,get:()=>separation,set:v=>{separation=v;refresh();}},{id:'bones',label:'Isolate / restore the selected bones',type:'button',set:()=>{boneView=!boneView;refresh();}},{id:'labels',label:'Show / hide muscle labels',type:'button',set:()=>annotations.visible=!annotations.visible}],stats:()=>[{label:'Muscle components',value:MUSCLES.length},{label:'Bone components',value:BONES.length},{label:'Source',value:'Registered anatomy'}],views:{overview:{position:[2.3,1.1,8.2],target:[0,0,0]},detail:{position:[1.2,1,4.9],target:[0,.55,0]}},note:'A selected upper-body muscle atlas, including separate heads and portions where supplied by BodyParts3D. The shoulder girdle, manubrium and first four rib pairs provide registered skeletal context. The head, lower ribs, many deep muscles and hands are not included. Separation is an exploded inspection view, not muscle motion. Surface striations are illustrative material detail, not measured fascicle direction. Source scale is enlarged 6.8× if scene units are metres.',craft:anatomyCredit,sources:[...anatomySources,{title:'OpenStax — Pectoral girdle and upper-limb muscles',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-5-muscles-of-the-pectoral-girdle-and-upper-limbs'}]});
}
